version: "3.9"

services:
  user_db:
    image: postgres
    container_name: user_db
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    networks:
      - test_git-network
    ports:
      - "5435:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data

networks:
  test_git-network:
    driver: bridge

volumes:
  postgres-user-data:
